import {selectedResearch} from './data';
import {byId,element} from './dom';
import {chartGeometry,exactNumber,sameCompany,type Identifier} from './state';
import type {ResearchView,Price,Fact} from './types';
import {financialsPanel} from './financials-panel';
export type ResearchTab='overview'|'financials'|'filings';
const identity=(item:ResearchView):Identifier|undefined=>item.binding?.record.company.candidate.identifier ?? item.data.rows.flatMap(row=>row.kind==='fact'?row.group.candidates.slice(0,1).map(c=>c.value.company):row.kind==='filing'||row.kind==='reported_fact'?[row.evidence.value.company]:row.kind==='candidate'?[row.entry.candidate.identifier]:[])[0] ?? queryCompany(item);
function queryCompany(item:ResearchView):Identifier|undefined {const query=item.data.header.query;const scope=query.scope as Record<string,unknown>|undefined;const company=(query.company??scope?.company) as Identifier|undefined;return company&&typeof company.namespace==='string'&&typeof company.value==='string'?company:undefined;}
function title(item:ResearchView,all:ResearchView[]){const company=identity(item);const known=all.flatMap(v=>v.data.rows.flatMap(row=>row.kind==='candidate'&&sameCompany(row.entry.candidate.identifier,company)?[row.entry.candidate.name]:[]))[0];const price=item.data.rows.find((row):row is Price=>row.kind==='price');return item.binding?.record.company.candidate.name??all.find(v=>v.binding&&sameCompany(v.binding.record.company.candidate.identifier,company))?.binding?.record.company.candidate.name??known??(company?company.value:price?.evidence.value.instrument.value)??'Research evidence';}
export function viewLabel(item:ResearchView,all:ResearchView[]){const kind=item.data.header.kind;const concept=typeof item.data.header.query.concept==='string'?item.data.header.query.concept.replace(/([a-z])([A-Z])/g,'$1 $2'):'';return `${title(item,all)} · ${kind==='prices'?'Price history':kind==='facts'?(concept||'Financials'):kind==='filings'?'Filings':kind==='resolution'?'Company matches':'Document'}`;}
const svgNode=(tag:string,attrs:Record<string,string>)=>{const node=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value] of Object.entries(attrs))node.setAttribute(key,value);return node;};
function pricePanel(item:ResearchView,range:string,onRange:(range:string)=>void){
 const root=element('section');const all=item.data.rows.filter((r):r is Price=>r.kind==='price').sort((a,b)=>a.evidence.value.date.localeCompare(b.evidence.value.date));
 const end=all.at(-1)?.evidence.value.date;const days=range==='1M'?31:range==='6M'?183:range==='1Y'?366:Infinity;
 const rows=all.filter(r=>!end||Date.parse(end)-Date.parse(r.evidence.value.date)<=days*86400000);
 const latest=rows.at(-1);const currencies=new Set(rows.map(p=>p.evidence.value.currency));
 root.append(element('p',latest?`${exactNumber(latest.value)} ${latest.evidence.value.currency}`:'No prices available','price-value'));
 root.append(element('p',latest?`Daily close · ${latest.evidence.value.date}`:'No price observations were returned.','price-description'));
 const buttons=element('div',undefined,'range-controls');for(const key of ['1M','6M','1Y','ALL']){const b=element('button',key);b.setAttribute('aria-pressed',String(key===range));b.onclick=()=>onRange(key);buttons.append(b);}root.append(buttons);
 if(currencies.size<=1){const plot=chartGeometry(rows.map(p=>({date:p.evidence.value.date,value:p.value})));const svg=svgNode('svg',{viewBox:'0 0 380 190',class:'price-chart',role:'img','aria-label':`Daily closing price history, ${rows[0]?.evidence.value.date??''} to ${end??''}; exact values in the table below`});for(const y of [20,70,120,170])svg.append(svgNode('line',{x1:'20',x2:'360',y1:String(y),y2:String(y),stroke:'#e0e7d8','stroke-width':'1'}));for(const d of plot.segments)svg.append(svgNode('path',{d,fill:'none',stroke:'#52753d','stroke-width':'2'}));for(const p of plot.points){const point=svgNode('circle',{cx:String(p.x),cy:String(p.y),r:plot.points.length===1?'4':'2',fill:'#52753d'});const caption=svgNode('title',{});caption.textContent=`${p.date}: ${p.value}`;point.append(caption);svg.append(point);}root.append(svg);const dates=element('div',undefined,'chart-dates');dates.append(element('span',rows[0]?.evidence.value.date??''),element('span',end??''));root.append(dates);}else root.append(element('p','Different currencies are present; inspect the exact observations below.','evidence-note'));
 const details=element('details');details.append(element('summary','Exact price observations'));const table=element('table');const head=element('tr');for(const label of ['Trading date','Close','Currency'])head.append(element('th',label));table.append(head);for(const row of rows){const tr=element('tr');for(const value of [row.evidence.value.date,exactNumber(row.value),row.evidence.value.currency])tr.append(element('td',value));table.append(tr);}details.append(table);root.append(details);
 root.append(element('p',`${item.data.header.coverage?.completeness??'Coverage not specified'} · ${all.length} of ${item.data.header.row_count} saved observations shown. Prices are historical, not live quotes.`,'evidence-note'));
 if(latest)root.append(element('p',`Retrieved ${latest.evidence.value.retrieved_at.slice(0,10)} · ${item.data.header.provider.instance_id}`,'source-note'));
 return root;
}
function factsPanel(items:ResearchView[]){const section=element('section',undefined,'financial-section');section.append(element('h3','Reported financials'));let count=0;
 const complete=items.find(item=>item.data.header.policy==='all-reported-facts-v1');if(complete){section.append(element('p',`${complete.data.header.row_count.toLocaleString()} financial observations are available. Open the Financials tab for the latest filings, every saved metric and full history.`,'evidence-note'));return section;}
 for(const item of items)for(const row of item.data.rows){if(row.kind!=='fact')continue;count++;const fact:Fact=row;const candidate=fact.group.candidates[0]?.value;const label=candidate?.label??candidate?.concept.replace(/([a-z])([A-Z])/g,'$1 $2')??'Reported metric';const metric=element('div',undefined,'metric');metric.append(element('span',label),element('strong',fact.group.conflict?'Conflicting reports':`${exactNumber(fact.group.value)}${candidate?' '+candidate.unit:''}`,fact.group.conflict?'conflict':''));const p=fact.group.period;metric.append(element('small',`${p.kind==='instant'?p.date:`${p.start} – ${p.end}`} · filed ${fact.group.filed} · ${item.data.header.provider.instance_id}`));section.append(metric);}
 if(!count)section.append(element('p','No reported fundamentals are open for this company yet. Ask the agent to inspect its financials.','evidence-note'));else section.append(element('p','Source-reported metrics and periods. Missing values remain missing; these are not assembled financial statements.','source-note'));return section;}
export function renderResearch(items:ResearchView[],selectedId:string|null,tab:ResearchTab,range:string,onRange:(r:string)=>void){
 const selected=selectedResearch(items,selectedId);if(!selected){byId('company-name').textContent='Company research';byId('company-listing').textContent='Charts & financial information';byId('company-icon').textContent='↗';byId('research-content').replaceChildren(element('p',selectedId?'The selected research view is unavailable. Its context will still be included unless removed below the composer.':'Ask the agent about a company to open its research here.','evidence-note'));return;}
 const company=identity(selected);const related=company?items.filter(i=>sameCompany(identity(i),company)):[selected];const name=title(selected,items);byId('company-name').textContent=name;byId('company-icon').textContent=name.slice(0,1).toUpperCase();const binding=selected.binding??related.find(i=>i.binding)?.binding;
 byId('company-listing').textContent=binding?`${binding.record.listing.ticker.value} · ${binding.record.listing.exchange?.value??'Exchange not specified'}`:company?`${company.namespace} · ${company.value}`:selected.data.header.provider.instance_id;
 const root=byId('research-content');const oldScroll=root.parentElement?.scrollTop??0;const content=element('div');
 if(tab==='overview'){const price=selected.data.header.kind==='prices'?selected:related.find(i=>i.data.header.kind==='prices');if(price)content.append(pricePanel(price,range,onRange));else content.append(element('p','No price chart is open for this company yet. Ask the agent for its price history.','evidence-note'));content.append(factsPanel(related));}
 if(tab==='financials'){const financial=selected.data.header.kind==='facts'?selected:[...related].filter(i=>i.data.header.kind==='facts').sort((a,b)=>b.data.header.created_at.localeCompare(a.data.header.created_at))[0];content.append(financialsPanel(financial));}
 if(tab==='filings'){let count=0;for(const item of related)for(const row of item.data.rows){if(row.kind==='filing'){count++;const filing=element('article',undefined,'filing');filing.append(element('strong',row.evidence.value.form),element('p',`Filed ${row.evidence.value.filed}`),element('p',row.evidence.value.source_url));content.append(filing);}}if(!count)content.append(element('p','No filing list is open for this company. Ask the agent to inspect its filings.','evidence-note'));}
 for(const issue of [...new Set(related.flatMap(item=>[...item.data.header.limitations,...item.data.header.conflicts]))])content.append(element('p',issue,'evidence-note'));
 if(selected.data.header.error)content.append(element('p',selected.data.header.error.message,'evidence-note'));
 if(selected.data.header.kind==='resolution')for(const row of selected.data.rows){if(row.kind==='candidate'){content.append(element('h3',row.entry.candidate.name),element('p',`${row.entry.candidate.identifier.namespace}: ${row.entry.candidate.identifier.value}`,'evidence-note'));}}
 root.replaceChildren(content);if(root.parentElement)root.parentElement.scrollTop=oldScroll;
}
