const {chromium}=require(process.env.LUGUS_PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs'),http=require('node:http'),cp=require('node:child_process'),readline=require('node:readline'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'lugus-portfolio-browser-'));
fs.writeFileSync(path.join(dir,'app.json'),JSON.stringify({financial_path:'financial.sqlite',application_path:'app.sqlite',providers:[]}));
fs.writeFileSync(path.join(dir,'desktop.json'),JSON.stringify({application_config:'app.json'}));
const child=cp.spawn(process.env.LUGUS_QA_BINARY||path.resolve(__dirname,'../src-tauri/target/debug/examples/portfolio_qa'),[path.join(dir,'desktop.json')],{stdio:['pipe','pipe','inherit']});
let pending=[];readline.createInterface({input:child.stdout}).on('line',line=>{const item=pending.shift();if(item)item(JSON.parse(line));});
function rpc(payload){return new Promise(resolve=>{pending.push(resolve);child.stdin.write(payload+'\n');});}
const root=path.resolve(__dirname,'../dist');
const server=http.createServer(async(req,res)=>{
 if(req.url==='/rpc'){let body='';for await(const chunk of req)body+=chunk;const result=await rpc(body);res.setHeader('content-type','application/json');res.end(JSON.stringify(result));return;}
 let file=path.resolve(root,'.'+(req.url==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.statusCode=403;res.end();return;}try{res.setHeader('content-type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}
});
(async()=>{let browser,page;try{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 browser=await chromium.launch({headless:true,executablePath:process.env.LUGUS_CHROMIUM,args:['--no-sandbox']});
 page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.__TAURI_INTERNALS__={invoke:async(cmd,args)=>{const r=await fetch('/rpc',{method:'POST',body:args.payload}).then(r=>r.json());if(r.error)throw r.error;return r.value;}};});
 await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.getByRole('button',{name:'Portfolio',exact:true}).click();
 await page.getByRole('button',{name:'Create portfolio',exact:true}).click();await page.getByLabel('Portfolio name').fill('QA Portfolio');await page.getByRole('button',{name:'Preview',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.locator('.portfolio-dialog').waitFor({state:'detached'});
 await page.locator('.portfolio-tabs').getByRole('button',{name:'Accounts',exact:true}).click();await page.getByRole('button',{name:'Add instrument',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Test equity');await page.getByLabel('Ticker',{exact:true}).fill('TEST');await page.getByRole('button',{name:'Preview',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.locator('.portfolio-dialog').waitFor({state:'detached'});
 await page.getByRole('button',{name:'Add account',exact:true}).click();await page.getByLabel('Account name').fill('Broker');await page.getByLabel('Start date').fill('2026-01-01');await page.getByRole('button',{name:'Preview',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.locator('.portfolio-dialog').waitFor({state:'detached'});
 async function trade(kind,fields){await page.getByRole('button',{name:'Add transaction',exact:true}).click();await page.getByLabel('Activity',{exact:true}).selectOption(kind);for(const [label,value]of Object.entries(fields))await page.getByLabel(label,{exact:true}).fill(value);await page.getByRole('button',{name:'Preview',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.locator('.portfolio-dialog').waitFor({state:'detached'});await page.getByRole('button',{name:'Add transaction',exact:true}).waitFor();}
 await trade('deposit',{'Amount (USD)':'200'});await trade('buy',{'Shares':'10','Execution price (USD)':'10','Fees (USD)':'1'});await trade('buy',{'Shares':'5','Execution price (USD)':'12'});await trade('sell',{'Shares':'12','Execution price (USD)':'15','Fees (USD)':'2'});
 await page.locator('.portfolio-tabs').getByRole('button',{name:'Overview',exact:true}).click();await page.getByText('$217.00',{exact:true}).first().waitFor();await page.getByText('Accounting & price details',{exact:true}).click();await page.getByText('$53.00',{exact:true}).waitFor();await page.screenshot({path:path.join(dir,'overview.png'),fullPage:true});
 await page.locator('.portfolio-tabs').getByRole('button',{name:'Holdings',exact:true}).click();await page.getByRole('button',{name:'TEST',exact:true}).click();await page.getByText('$36.00',{exact:true}).first().waitFor();await page.screenshot({path:path.join(dir,'holdings.png'),fullPage:true});await page.keyboard.press('Escape');

 await page.locator('.portfolio-tabs').getByRole('button',{name:'Accounts',exact:true}).click();await page.getByRole('button',{name:'Add account',exact:true}).click();await page.getByLabel('Account name').fill('Existing broker');await page.getByLabel('Start date').fill('2026-01-01');await page.getByLabel('Starting point',{exact:true}).selectOption('existing');await page.getByLabel('Opening cash (USD)',{exact:true}).fill('39');
 for(const [date,qty,basis]of [['2025-01-01','10','101'],['2025-02-01','5','60']]){await page.getByRole('button',{name:'Add purchase lot',exact:true}).click();const group=page.locator('.portfolio-dialog fieldset').last();await group.getByLabel('Original purchase date',{exact:true}).fill(date);await group.getByLabel('Remaining shares').fill(qty);await group.getByLabel('Remaining total cost basis, including fees (USD)').fill(basis);}
 await page.getByRole('button',{name:'Preview',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.locator('.portfolio-dialog').waitFor({state:'detached'});await page.getByLabel('Account',{exact:true}).selectOption({label:'Existing broker'});await page.getByRole('button',{name:'Add transaction',exact:true}).waitFor();await trade('sell',{'Shares':'12','Execution price (USD)':'15','Fees (USD)':'2'});await page.getByLabel('Account',{exact:true}).selectOption({label:'Existing broker'});await page.locator('.portfolio-tabs').getByRole('button',{name:'Overview',exact:true}).click();await page.getByText('$217.00',{exact:true}).first().waitFor();await page.getByText('Accounting & price details',{exact:true}).click();await page.getByText('$53.00',{exact:true}).waitFor();await page.screenshot({path:path.join(dir,'opening-account.png'),fullPage:true});
 await page.getByRole('button',{name:'Use in chat',exact:true}).click();await page.getByText(/Portfolio snapshot as of .* will be shared/).waitFor();
 if(errors.length)throw new Error(errors.join('\n'));console.log(JSON.stringify({passed:true,artifact_dir:dir,checks:['create portfolio','instrument','full-history account','deposit','two buys','FIFO sale','cash 217','realized pnl 53','remaining shares 3 and basis 36','equivalent opening lots and subsequent FIFO sale','snapshot selection'],page_errors:errors}));
 }catch(e){console.error(e);if(page){console.error(await page.locator('body').innerText());await page.screenshot({path:path.join(dir,'failure.png'),fullPage:true});console.error(dir);}process.exitCode=1;}finally{if(browser)await browser.close();server.close();child.stdin.end();}})();
