import type {View,Page,LotRow,TransactionRow} from './types';
import type {PortfolioApi} from './api';
import {node,button,errorText} from './forms';
import {formatMoney,formatPercent} from './format';
export interface ResearchIntent {instrumentId:string;symbol:string;name:string}
export function openHoldingDetail(api:PortfolioApi,view:View,accountId:string|null,id:string,trigger:HTMLElement,onResearch:(intent:ResearchIntent)=>Promise<void>){
 const holding=view.valuation.holdings.find(h=>h.instrument_id===id),instrument=view.instruments.find(i=>i.id===id);if(!holding||!instrument)return()=>{};
 let alive=true;const dialog=node('dialog',undefined,'portfolio-drawer');const title=node('h2',instrument.symbol);title.id=`holding-${crypto.randomUUID()}`;dialog.setAttribute('aria-labelledby',title.id);const close=button('Close holding',()=>dialog.close());close.className='portfolio-drawer-close';dialog.append(close,node('p',instrument.asset_kind==='stock'?'Stock · USD':'ETF · USD','portfolio-muted'),title,node('p',instrument.name,'portfolio-muted'),node('p',formatMoney(holding.market_value),'portfolio-number'));
 const grid=node('dl',undefined,'portfolio-detailgrid');const gain=view.dashboard?.holdings.find(h=>h.instrument_id===id)?.unrealized_percent??null;
 for(const [label,value]of [['Shares',holding.quantity],['Cost basis',formatMoney(holding.basis)],['Unrealized gain / loss',formatMoney(holding.unrealized)],['Return on cost',formatPercent(gain,true)],['Portfolio weight',formatPercent(holding.allocation_percent)],['Price',holding.price?`${formatMoney(holding.price.close)} · ${holding.price.date}`:'Unpriced']]){const cell=node('div');cell.append(node('dt',label),node('dd',value));grid.append(cell);}dialog.append(grid);
 if(holding.unpriced_reason)dialog.append(node('p',holding.unpriced_reason,'portfolio-notice'));if(holding.simplified)dialog.append(node('p','Includes simplified opening purchase history.','portfolio-notice'));
 const status=node('p');status.setAttribute('role','status');dialog.append(status);
 const research=button(`Research ${instrument.symbol}`,async()=>{research.disabled=true;try{await onResearch({instrumentId:id,symbol:instrument.symbol,name:instrument.name});dialog.close();}catch(e){status.textContent=errorText(e);}finally{research.disabled=false;}});research.className='portfolio-research-button';dialog.append(research,node('p','Adds this portfolio context and a draft question to chat. You review and send it.','portfolio-muted'));
 for(const section of ['lots','transactions']as const){const region=node('section');region.append(node('h3',section==='lots'?'Remaining lots':'Recent activity'));const content=node('div',undefined,'portfolio-tablewrap');region.append(content);dialog.append(region);
  const load=async(offset:number)=>{content.replaceChildren(node('p','Loading…'));try{const page=await api<Page<LotRow|TransactionRow>>({kind:'holding_rows',portfolio_id:view.id,account_id:accountId,instrument_id:id,section,offset,revision:view.revision});if(!alive)return;if(page.revision!==view.revision)throw new Error('Portfolio changed. Reopen this holding.');const table=node('table'),head=node('tr');for(const label of section==='lots'?['Account','Acquired','Shares','Basis']:['Date','Account','Activity','Amount / shares'])head.append(node('th',label));table.append(head);for(const item of page.items){const row=node('tr');const values='lot'in item?[item.account_name,item.lot.acquired,item.lot.quantity,formatMoney(item.lot.basis)]:[item.event.date,item.account_name,item.event.kind.kind,item.event.kind.amount?formatMoney(String(item.event.kind.amount)):String(item.event.kind.quantity??`${item.event.kind.numerator}:${item.event.kind.denominator}`)];for(const value of values)row.append(node('td',value));table.append(row);}content.replaceChildren(page.items.length?table:node('p',section==='lots'?'No remaining lots.':'No recorded activity.'));const nav=node('div',undefined,'portfolio-actions');if(offset>0)nav.append(button('First page',()=>load(0)));if(page.next_offset!==null)nav.append(button('Next page',()=>load(page.next_offset!)));content.append(nav);}catch(e){if(alive)content.replaceChildren(node('p',errorText(e)));}};void load(0);
 }
 dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 dialog.addEventListener('close',()=>{alive=false;dialog.remove();if(trigger.isConnected)trigger.focus();});document.body.append(dialog);dialog.showModal();close.focus();return()=>{alive=false;dialog.close();};
}
