import type {PerformancePoint,PortfolioHistoryHeader,PortfolioHistoryPage,HistoryEvidencePage} from './types';
import type {Period,ChartMode} from './history-state';
import {historyGeometry,sampleHistory,hasFlow,portfolioPlotValue} from './history-geometry';
import {node,button,errorText} from './forms';
import {formatMoney,formatPercent} from './format';
export function mountPerformance(root:HTMLElement,callbacks:{onEvidencePage:(offset:number)=>Promise<HistoryEvidencePage>;onPeriod:(period:Period)=>void;onRefresh:()=>void;onCancel:()=>void;onDataPage:(offset:number)=>Promise<PortfolioHistoryPage>},initial:Period='YTD'){
 let mode:ChartMode='return',period=initial,header:PortfolioHistoryHeader|null=null,rows:PerformancePoint[]=[],alive=true,stale=false,dataGeneration=0,evidenceGeneration=0;
 const head=node('div',undefined,'portfolio-cardhead');head.append(node('h2','Performance'));const modes=node('div',undefined,'portfolio-segmented');head.append(modes);const tools=node('div',undefined,'portfolio-charttools');const legend=node('div',undefined,'portfolio-legend');const portfolioLabel=node('span','● My portfolio');const benchmarkLabel=node('span','● S&P 500 total return');benchmarkLabel.className='portfolio-benchmark';legend.append(portfolioLabel,benchmarkLabel);const periods=node('div',undefined,'portfolio-segmented');tools.append(legend,periods);
 const status=node('p',undefined,'portfolio-muted');status.setAttribute('role','status');const chart=node('div',undefined,'portfolio-chart');const inspection=node('output',undefined,'portfolio-inspection');inspection.setAttribute('aria-live','polite');const method=node('p',undefined,'portfolio-muted');const actions=node('div',undefined,'portfolio-actions');const refresh=button('Refresh history',callbacks.onRefresh),cancel=button('Cancel history',callbacks.onCancel);cancel.hidden=true;actions.append(refresh,cancel);const tableDetails=node('details',undefined,'portfolio-history-data');tableDetails.append(node('summary','View exact daily data'));const data=node('div',undefined,'portfolio-tablewrap');tableDetails.append(data);root.append(head,tools,status,chart,inspection,method,actions,tableDetails);
 const methodology=node('details',undefined,'portfolio-history-methodology');methodology.append(node('summary','Methodology & sources'),node('p','Return is compounded from daily growth: (closing value + withdrawals) ÷ (previous closing value + deposits + opening contribution). Inflows are treated as available for the day; withdrawals occur after daily growth. Existing accounts enter at market value on their setup date. The S&P 500 total-return index (^SP500TR) already includes reinvested dividends.','portfolio-muted'));const sources=node('div');methodology.append(sources);root.append(methodology);
 async function evidencePage(offset:number){const generation=++evidenceGeneration;sources.replaceChildren(node('p','Loading sources…'));try{const page=await callbacks.onEvidencePage(offset);if(!alive||generation!==evidenceGeneration)return;sources.replaceChildren();for(const e of page.items){const card=node('article');const manifest=e.manifest;card.append(node('strong',`${manifest?.instrument.value??'Historical prices'} · ${e.provider.instance_id} (${e.provider.plugin_id} ${e.provider.plugin_version})`));if(manifest)card.append(node('p',`Observed ${manifest.coverage_start} through ${manifest.last_completed_session}. Retrieved ${manifest.retrieved_at}. Split normalization anchor ${manifest.anchor}; ${manifest.calendar} calendar ${manifest.calendar_version}.`));if(e.source_url){try{const url=new URL(e.source_url);if(url.protocol==='https:'||url.protocol==='http:'){const link=node('a','Source price history');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';card.append(link);}}catch{}}sources.append(card);}if(!page.items.length)sources.append(node('p','No source price history was available for this result.'));if(page.next_offset!==null)sources.append(button('More sources',()=>evidencePage(page.next_offset!)));}catch(e){if(alive&&generation===evidenceGeneration)sources.replaceChildren(node('p',errorText(e)));}}
 methodology.addEventListener('toggle',()=>{if(methodology.open&&header)void evidencePage(0);});
 for(const [value,label]of [['return','Return %'],['value','Value $']]as const){const b=button(label,()=>{mode=value;draw();});b.dataset.mode=value;modes.append(b);}
 for(const value of ['1M','3M','YTD','1Y','All']as const){const b=button(value,()=>{period=value;setPeriod();callbacks.onPeriod(value);});b.dataset.period=value;periods.append(b);}
 function setPeriod(){for(const b of periods.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.period===period));}setPeriod();
 const exact=(value:string|null,unit:string)=>value===null?'Unavailable':`${value} ${unit}`;
 async function dataPage(offset:number){const generation=++dataGeneration;data.replaceChildren(node('p','Loading daily data…'));try{const page=await callbacks.onDataPage(offset);if(!alive||generation!==dataGeneration)return;const table=node('table');const head=node('thead'),tr=node('tr');for(const text of ['Date','Value','Portfolio return','S&P 500 return','Hypothetical value','Deposits','Opening contribution','Withdrawals','Coverage']){const th=node('th',text);th.scope='col';tr.append(th);}head.append(tr);table.append(head);const body=node('tbody');for(const row of page.items){const tr=node('tr');for(const value of [row.date,exact(row.value,'USD'),exact(row.portfolio_return_percent,'%'),exact(row.benchmark_return_percent,'%'),exact(row.hypothetical_value,'USD'),exact(row.deposits,'USD'),exact(row.opening_contribution,'USD'),exact(row.withdrawals,'USD'),row.issues.map(i=>i.code.replaceAll('_',' ')).join('; ')||'Available'])tr.append(node('td',value));body.append(tr);}table.append(body);data.replaceChildren(table);const nav=node('div',undefined,'portfolio-actions');if(offset>0)nav.append(button('First dates',()=>dataPage(0)));if(page.next_offset!==null)nav.append(button('Next dates',()=>dataPage(page.next_offset!)));data.append(nav);}catch(e){if(alive&&generation===dataGeneration)data.replaceChildren(node('p',errorText(e)));}}
 tableDetails.addEventListener('toggle',()=>{if(tableDetails.open&&header)void dataPage(0);});
 function draw(){
  for(const b of modes.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.mode===mode));benchmarkLabel.textContent=mode==='return'?'● S&P 500 total return':'● Same cash flows in S&P 500';
  method.textContent=mode==='return'?'Daily time-weighted returns include dividends and fees. Deposits, withdrawals and opening balances are accounted for. Gaps indicate unavailable returns.':'Portfolio value includes cash. The benchmark shows a hypothetical investment with the same external cash flows; it stops if a withdrawal would exceed its balance.';
  if(rows.some(r=>r.segment>0))method.textContent+=' New return segments restart at recapitalization; the full-period return is unavailable.';
  chart.replaceChildren();inspection.textContent='';if(!rows.length){chart.append(node('p','Historical data will appear here.','portfolio-empty-chart'));return;}
  const sampled=sampleHistory(rows,650),geometry=historyGeometry(sampled,mode),full=historyGeometry(rows,mode);const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 1000 270');svg.setAttribute('role','img');svg.setAttribute('aria-label',`${mode==='return'?'Return':'Value'} comparison. Use left and right arrow keys to inspect dates.`);svg.setAttribute('tabindex','0');
  const element=(tag:string,attrs:Record<string,string>,text?:string)=>{const n=document.createElementNS(ns,tag);for(const [key,value]of Object.entries(attrs))n.setAttribute(key,value);if(text!==undefined)n.textContent=text;svg.append(n);return n;};
  for(let i=0;i<5;i++){const y=30+i*50;const value=geometry.max-(geometry.max-geometry.min)*i/4;element('line',{x1:'70',x2:'970',y1:String(y),y2:String(y),class:'portfolio-gridline'});element('text',{x:'60',y:String(y+4),'text-anchor':'end',class:'portfolio-axis'},new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(value)+(mode==='return'?'%':''));}
  for(const path of geometry.benchmark)element('path',{d:path,fill:'none',class:'portfolio-benchmark-line'});for(const path of geometry.portfolio)element('path',{d:path,fill:'none',class:'portfolio-series-line'});
  for(const [i,row]of sampled.entries())if(hasFlow(row)){const p=geometry.points[i];element('circle',{cx:String(p.x),cy:'238',r:'3',class:'portfolio-flow-marker'});}
  element('text',{x:'70',y:'260',class:'portfolio-axis'},rows[0].date);element('text',{x:'970',y:'260','text-anchor':'end',class:'portfolio-axis'},rows.at(-1)!.date);
  const cursor=element('line',{x1:'70',x2:'70',y1:'25',y2:'235',class:'portfolio-chart-cursor'});let selected=rows.length-1;
  const inspect=(index:number)=>{selected=Math.max(0,Math.min(rows.length-1,index));const row=rows[selected],p=full.points[selected];cursor.setAttribute('x1',String(p.x));cursor.setAttribute('x2',String(p.x));const portfolio=portfolioPlotValue(row,mode);inspection.textContent=`${row.date} · Portfolio ${mode==='return'?formatPercent(portfolio,true):formatMoney(portfolio)}${row.segment>0?' (new return segment)':''} · S&P 500 ${mode==='return'?formatPercent(row.benchmark_return_percent,true):formatMoney(row.hypothetical_value)}${hasFlow(row)?` · Deposits ${formatMoney(row.deposits)}, opening contribution ${formatMoney(row.opening_contribution)}, withdrawals ${formatMoney(row.withdrawals)}`:''}${row.issues.length?' · '+[...new Set(row.issues.map(i=>i.code.replaceAll('_',' ')))].join(', '):''}`;};
  svg.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();inspect(e.key==='Home'?0:e.key==='End'?rows.length-1:selected+(e.key==='ArrowRight'?1:-1));}});
  svg.addEventListener('pointermove',e=>{const rect=svg.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width*1000;inspect(Math.round((x-70)/900*(rows.length-1)));});chart.append(svg);inspect(selected);
 }
 return{
  clear(){header=null;rows=[];dataGeneration++;evidenceGeneration++;tableDetails.open=false;methodology.open=false;data.replaceChildren();sources.replaceChildren();draw();},
  loading(){status.textContent=header?'Refreshing saved history…':'Loading historical performance…';cancel.hidden=false;refresh.disabled=true;},
  render(next:PortfolioHistoryHeader,points:PerformancePoint[],saved:boolean){header=next;rows=points;stale=saved;status.textContent=`${stale?'Saved result · ':''}${next.status.replaceAll('_',' ')} · ${next.baseline??'Unknown baseline'} → ${next.effective_end??'Unknown end'}${next.issue_count?` · ${next.issue_count} coverage notes; see daily data`:''}${next.evidence_count?' · Source completeness unverified':''}${next.issues.some(i=>i.code==='benchmark_selection_required')?' · Choose a benchmark source in Accounts.':''}${next.error?` · ${next.error}`:''}`;cancel.hidden=true;refresh.disabled=false;draw();if(tableDetails.open)void dataPage(0);if(methodology.open)void evidencePage(0);},
  fail(message:string){status.textContent=message;cancel.hidden=true;refresh.disabled=false;},
  setOnline(online:boolean){refresh.disabled=!online;refresh.title=online?'':'History refresh is unavailable offline';},
  dispose(){alive=false;dataGeneration++;root.replaceChildren();},
 };
}
