export type Decimal=string;
export interface Page<T>{items:T[];next_offset:number|null;revision:string}
export interface Header{id:string;name:string;currency:string;revision:string}
export interface Instrument{id:string;name:string;symbol:string;asset_kind:'stock'|'etf';currency:string;binding:{instance_id:string;native_id:{namespace:string;value:string}}|null}
export interface OpeningLot{id:string;instrument_id:string;acquired:string;tie_order:number;quantity:string;basis:string;simplified:boolean;date_assumed:boolean}
export type Opening={kind:'full_history'}|{kind:'existing';cash:string;lots:OpeningLot[]};
export interface Account{id:string;name:string;revision:string;start:string;opening?:Opening;simplified?:boolean}
export interface Event{id:string;date:string;order:number;kind:Record<string,unknown>&{kind:string}}
export interface TransactionRow{account_id:string;account_name:string;event:Event}
export interface Lot{id:string;instrument_id:string;acquired:string;quantity:string;basis:string;simplified:boolean}
export interface LotRow{account_id:string;account_name:string;lot:Lot}
export interface Holding{instrument_id:string;quantity:string;basis:string;market_value:string|null;unrealized:string|null;price:{close:string;date:string}|null;unpriced_reason:string|null;allocation_percent:string|null;simplified:boolean}
export interface View{id:string;name:string;revision:string;as_of:string;accounts:Account[];instruments:Instrument[];valuation:{cash:string;holdings:Holding[];priced_subtotal:string;total_value:string|null;unrealized:string|null;complete:boolean;cash_allocation_percent:string|null};realized:string;dividends:string;standalone_fees:string;trade_fees:string;deposits:string;withdrawals:string;price_status:string[]}
export interface Command{request_id:string;portfolio_id:string|null;expected_revision:string;mutation:Record<string,unknown>}
export interface Receipt{portfolio_id:string;revision:string;account_ids:string[];instrument_ids:string[]}
export interface Preview{view:View;states:{account_id:string;matches:{sale_id:string;lot_id:string;quantity:string;basis:string;net_proceeds:string;realized:string;simplified:boolean}[]}[]}
export interface Snapshot{id:string;summary:View;created_at:string}
export interface Audit{request_id:string;revision:string;recorded_at:string;mutation:Record<string,unknown>}
